### ISSUE TITLE
water level vs sensor depth vs gage height

### ISSUE THREAD

**Issue by JenStamp** [leppott/ContDataQC#100]
Hi Erik, 
We’re running into the water level/sensor depth/gage height issue again. We are working with files that come with one of the following three labels for water level -
•	Sensor Depth = HOBOware output if they don’t enter a reference water level
•	Water Level = HOBOware output if they enter a reference water level
•	GageHeight ft - from USGS NWIS site

At this point it’s a fairly even mix of people generating sensor depth vs. water level outputs. Knowing what we know now, it’s probably important to keep that distinction. 

Right now, we have the following two entries in the config file: sensor depth and gage height. 

Possible options – 
•	Enter ‘Water Level’ into the config file as a third option
•	If we want to stick with two possible entries vs entering ‘Water Level’ into the config file as a third option, I’d vote for changing GageHeight to WaterLevel. If people use USGS gage data, their focus will be on discharge, not GageHeight. 
o	If we still want to carry GageHeight through (probably a good idea), perhaps you can have it change ‘GageHeight’ to ‘WaterLevel’ when R reformats the file coming in from NWIS. Then we'll be able to stick with two possible entries.

Thanks for your help on this!

**Comment by leppott** [comment]
Works now with v2.0.5.9056  
https://github.com/leppott/ContDataQC/commit/78bfe009e12ef8cacb7810227013835931619ad3

**Comment by leppott** [comment]
* changed gage height to water level
* converted USGS gage height to water level
*  Made changes elsewhere to make it work.

**Comment by leppott** [comment]
Update formatHobo() to use water level.

**Comment by leppott** [comment]
Water level not showing in output file.

Fixed in v2.0.5.9060.
https://github.com/leppott/ContDataQC/commit/8f22dab4bbcabdc052fe965f50d3f6f26e8e0f06
