### ISSUE TITLE
get gage data - missing initial measurements for the start date and spilling into the next day on the other end

### ISSUE THREAD

**Issue by JenStamp** [leppott/ContDataQC#101]
not sure there is any way we can address this, but when I use the 'get gage data' function, and plug in 1/1/2015, the output is missing the first set of measurements for that day (its starting measurement is 1/1/2015  5:00:00 AM). when I plug in 12/31/2015 as my end date, it spills over into the next day (its ending measurement is 1/1/2016  4:45:00 AM). if you want data for a particular date range, I'm not sure there's a way to deal with this offset issue other than manually trimming the end measurements and using the previous day (in this example, 12/31/2014) as the starting date (which I'm fine doing, I just wanted to bring it to your attention in case there's a slick fix you can come up with...but not a high priority item right now). Thanks!

**Comment by leppott** [comment]
Data is reported with timezone UTC (-5 hrs from eastern time).

![image](https://user-images.githubusercontent.com/24276278/103552255-9f90ac00-4e79-11eb-8ada-92ab51c65a30.png)

https://cran.r-project.org/web/packages/dataRetrieval/vignettes/dataRetrieval.html#unit-data
![image](https://user-images.githubusercontent.com/24276278/103552515-06ae6080-4e7a-11eb-9469-dfe915ed65b5.png)


If change timezone to America/New_York get the same data with the timezone changed (and the time changed by 5 hours).

![image](https://user-images.githubusercontent.com/24276278/103552453-ee3e4600-4e79-11eb-8939-ff66b29afeeb.png)

**Comment by leppott** [comment]
Not an issue with the Shiny app.  The app is getting the same results as the dataRetrieval package on its own.

Need to have users be mindful of their own time zone.  

It is interesting that the R package while reporting the data with UTC time zone filters the data by the local time of the gage (NC so eastern US).

![image](https://user-images.githubusercontent.com/24276278/103552932-ad92fc80-4e7a-11eb-91c3-67aa70b7e11e.png)

**Comment by leppott** [comment]
If select a time zone other than the one with the gage still get data based on the gage's time zone.  (Just like if don't select a time zone and get UTC).

![image](https://user-images.githubusercontent.com/24276278/103553526-90aaf900-4e7b-11eb-97ff-f78b2b970ee2.png)
