### ISSUE TITLE
unable to run USGS gage file through QC function

### ISSUE THREAD

**Issue by JenStamp** [leppott/ContDataQC#99]
Hey Erik, I was able to successfully download gage data from the Shiny app but when I tried to run it through the QC function, it kicked me out. I'll email you the file I was trying to use. Hopefully it's not a big deal to troubleshoot. Thanks!

**Comment by leppott** [comment]
Works now with v2.0.5.9056  
https://github.com/leppott/ContDataQC/commit/78bfe009e12ef8cacb7810227013835931619ad3
